In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Load dataset
file_path = "combined_simulated.csv"  # Update this path if needed
df = pd.read_csv(file_path)

In [3]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

def run_pca(file_path, n_components=5):
    # Load dataset
    df = pd.read_csv(file_path)

    # Drop non-numeric columns
    df_numeric = df.select_dtypes(include=[np.number])

    # Standardize the data
    scaler = StandardScaler()
    df_scaled = scaler.fit_transform(df_numeric)

    # Apply PCA
    pca = PCA(n_components=n_components)
    principal_components = pca.fit_transform(df_scaled)

    # Create a DataFrame with principal components
    pca_df = pd.DataFrame(principal_components, columns=[f'PC{i+1}' for i in range(n_components)])

    # Explained variance ratio
    explained_variance = pca.explained_variance_ratio_
    print("Explained Variance Ratio per PC:", explained_variance)
    print("Cumulative Explained Variance:", np.cumsum(explained_variance))

    # Get feature importance (absolute values of PCA component loadings)
    loadings = pd.DataFrame(pca.components_, columns=df_numeric.columns, index=[f'PC{i+1}' for i in range(n_components)])

    # Rank features by their absolute contribution to PC1
    feature_importance = loadings.loc["PC1"].abs().sort_values(ascending=False)

    # Top 10 most important features
    top_10_features = feature_importance.head(10)
    print("\nTop 10 most important features for PC1:")
    print(top_10_features)

    return top_10_features

# Run PCA and get top 10 features

top_features = run_pca(file_path)

Explained Variance Ratio per PC: [0.31493719 0.14862621 0.09723175 0.06805881 0.06457052]
Cumulative Explained Variance: [0.31493719 0.4635634  0.56079515 0.62885396 0.69342448]

Top 10 most important features for PC1:
EXPECTED_FOB          0.305612
FUEL_IN_TANKS         0.300676
VALUE_FOB             0.300662
VALUE_FUEL_QTY_LXT    0.299884
VALUE_FUEL_QTY_RXT    0.297503
TOTAL_FUEL_LW         0.297184
TOTAL_FUEL_RW         0.294962
FUEL_USED_4           0.243927
TOTAL_FUEL_USED       0.243720
FUEL_USED_3           0.243708
Name: PC1, dtype: float64


In [4]:
# Display dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 376554 entries, 0 to 376553
Data columns (total 35 columns):
 #   Column                     Non-Null Count   Dtype  
---  ------                     --------------   -----  
 0   UTC_TIME                   376554 non-null  object 
 1   FUEL_USED_2                376554 non-null  float64
 2   FUEL_USED_3                376554 non-null  float64
 3   FUEL_USED_4                376554 non-null  float64
 4   FW_GEO_ALTITUDE            376554 non-null  float64
 5   VALUE_FOB                  376554 non-null  float64
 6   VALUE_FUEL_QTY_CT          376554 non-null  float64
 7   VALUE_FUEL_QTY_FT1         376554 non-null  float64
 8   VALUE_FUEL_QTY_FT2         376554 non-null  float64
 9   VALUE_FUEL_QTY_FT3         376554 non-null  float64
 10  VALUE_FUEL_QTY_FT4         376554 non-null  float64
 11  VALUE_FUEL_QTY_LXT         376554 non-null  float64
 12  VALUE_FUEL_QTY_RXT         376554 non-null  float64
 13  FLIGHT_PHASE_COUNT         37

In [5]:
# Convert UTC_TIME to datetime format if it's not already
df['UTC_TIME'] = pd.to_datetime(df['UTC_TIME'])

# Sort by FLIGHT_ID and UTC_TIME
df_sorted = df.sort_values(by=['FLIGHT_ID', 'UTC_TIME'])

# Reset index
df_sorted = df_sorted.reset_index(drop=True)

In [6]:
df = df.drop(columns=['FLIGHT_PHASE_COUNT','Flight','FLIGHT_INSTANCE'])

## Model Setups

In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

def split_train_test(df, leak_column="LEAK_FLOW_FLAG", test_size=0.15):
    """
    Splits the dataset into train and test sets while maintaining the chronological order.
    Ensures the same proportion of leaks in train and test sets.
    """
    #df = df.sort_values(by="UTC_TIME")  # Sort by time to prevent data leakage

    split_idx = int(len(df) * (1 - test_size))  # Compute split index
    train_df = df.iloc[:split_idx]
    test_df = df.iloc[split_idx:]

    # Count the number of leaks in each dataset
    train_leak_count = train_df['LEAK_FLOW_FLAG'].sum()
    test_leak_count = test_df['LEAK_FLOW_FLAG'].sum()
    total_leak_count = df['LEAK_FLOW_FLAG'].sum()
    # Compute expected leak split (should be 75%-25%)
    expected_train_leaks = int(total_leak_count * 0.85)
    expected_test_leaks = total_leak_count - expected_train_leaks

    # Display class distributions
    print(f"Total Leak Count: {total_leak_count}")
    print(f"Train set leak rate: {100 * train_df[leak_column].mean():.4f}% == Training Leak Count: {train_leak_count} (Expected: {expected_train_leaks}) ")
    print(f"Test set leak rate: {100 * test_df[leak_column].mean():.4f}% == Testing Leak Count: {test_leak_count} (Expected: {expected_test_leaks})")
    print(f"Training Data Shape: {train_df.shape}, Testing Data Shape: {test_df.shape}")

    return train_df, test_df

# Apply split
train_df, test_df = split_train_test(df)


Total Leak Count: 33475
Train set leak rate: 8.2841% == Training Leak Count: 26515 (Expected: 28453) 
Test set leak rate: 12.3221% == Testing Leak Count: 6960 (Expected: 5022)
Training Data Shape: (320070, 32), Testing Data Shape: (56484, 32)


Autoencoder

In [8]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from keras.models import Model
from keras.layers import Input, Dense
from keras import regularizers
import numpy as np

# Filter out the entries with leaks from training data
train_data = train_df[train_df['LEAK_FLOW_FLAG'] == 0].drop(columns=['LEAK_FLOW_FLAG'])

# Identify numerical columns and scale only those
numerical_cols = train_data.select_dtypes(include=[np.number]).columns
scaler = MinMaxScaler()
train_data_scaled = scaler.fit_transform(train_data[numerical_cols])

# Define the autoencoder model architecture
input_dim = train_data_scaled.shape[1]  # Number of features
encoding_dim = 14  # Dimension of the encoded representation

# Input layer
input_layer = Input(shape=(input_dim,))
# Encoder layers
encoder = Dense(encoding_dim, activation="tanh", activity_regularizer=regularizers.l1(10e-5))(input_layer)
encoder = Dense(int(encoding_dim / 2), activation="relu")(encoder)
# Decoder layers
decoder = Dense(int(encoding_dim / 2), activation='tanh')(encoder)
decoder = Dense(input_dim, activation='relu')(decoder)

# Define the autoencoder model
autoencoder = Model(inputs=input_layer, outputs=decoder)
autoencoder.compile(optimizer='adam', loss='mean_squared_error')

# Train the autoencoder on the scaled training data
autoencoder.fit(train_data_scaled, train_data_scaled,
                epochs=50,
                batch_size=32,
                shuffle=False,
                validation_split=0.2,
                verbose=1)

# Prepare the test data by selecting only numerical columns and scaling
test_data = test_df[numerical_cols]
test_data_scaled = scaler.transform(test_data)

# Get the reconstruction loss (MSE) on the test data
reconstructions = autoencoder.predict(test_data_scaled)
mse = np.mean(np.power(test_data_scaled - reconstructions, 2), axis=1)

# Determine the threshold for anomaly detection based on 95th percentile of MSE
threshold = np.percentile(mse, 95)

# Detect anomalies based on the threshold
test_df = test_df.copy()  # Avoid SettingWithCopyWarning
test_df['reconstruction_error'] = mse
test_df['anomaly'] = test_df['reconstruction_error'] > threshold

# Calculate evaluation metrics: Confusion Matrix, Accuracy, Precision, Recall, F1 Score
y_true = test_df['LEAK_FLOW_FLAG']  # True labels
y_pred = test_df['anomaly'].astype(int)  # Predicted labels (0 or 1)

conf_matrix = confusion_matrix(y_true, y_pred)  # Confusion Matrix
accuracy = accuracy_score(y_true, y_pred)  # Accuracy
precision = precision_score(y_true, y_pred, zero_division=0)  # Precision
recall = recall_score(y_true, y_pred, zero_division=0)  # Recall
f1 = f1_score(y_true, y_pred, zero_division=0)  # F1 Score

# Print the evaluation results
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")


Epoch 1/50
7339/7339 ━━━━━━━━━━━━━━━━━━━━ 14s 2ms/step - loss: 0.0402 - val_loss: 0.0120
Epoch 2/50
7339/7339 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 0.0088 - val_loss: 0.0071
Epoch 3/50
7339/7339 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - loss: 0.0071 - val_loss: 0.0067
Epoch 4/50
7339/7339 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 0.0069 - val_loss: 0.0072
Epoch 5/50
7339/7339 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 0.0067 - val_loss: 0.0065
Epoch 6/50
7339/7339 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 0.0066 - val_loss: 0.0074
Epoch 7/50
7339/7339 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 0.0066 - val_loss: 0.0064
Epoch 8/50
7339/7339 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 0.0065 - val_loss: 0.0068
Epoch 9/50
7339/7339 ━━━━━━━━━━━━━━━━━━━━ 44s 3ms/step - loss: 0.0064 - val_loss: 0.0055
Epoch 10/50
7339/7339 ━━━━━━━━━━━━━━━━━━━━ 6s 843us/step - loss: 0.0063 - val_loss: 0.0071
Epoch 11/50
7339/7339 ━━━━━━━━━━━━━━━━━━━━ 7s 960us/step - loss: 0.0063 - val_loss: 0.0054
Epoch 12/50
7339/

Isolation Forest

In [9]:
from sklearn.ensemble import IsolationForest
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
import pandas as pd
import numpy as np

# Remove unwanted columns from training and test data
test_df = test_df.drop(columns=['reconstruction_error'], errors='ignore')
train_df = train_df.drop(columns=['reconstruction_error'], errors='ignore')

# Extract numerical features for training and testing
train_x = train_df.select_dtypes(include=[np.number]).drop(columns=['LEAK_FLOW_FLAG'])
test_x = test_df.select_dtypes(include=[np.number]).drop(columns=['LEAK_FLOW_FLAG'])

# Create an Isolation Forest model
isolation_forest = IsolationForest(contamination=0.025, random_state=42)

# Fit the model on training data
isolation_forest.fit(train_x)

# Predict anomalies
train_x_predictions = isolation_forest.predict(train_x)
test_x_predictions = isolation_forest.predict(test_x)

# Convert predictions to binary labels (-1 indicates an anomaly)
train_x_predictions = (train_x_predictions == -1).astype(int)
test_x_predictions = (test_x_predictions == -1).astype(int)

# Print the confusion matrix for training data
cm_train = confusion_matrix(train_df['LEAK_FLOW_FLAG'], train_x_predictions)
print("Training Confusion Matrix:\n", cm_train)

# Print the confusion matrix for test data
cm_test = confusion_matrix(test_df['LEAK_FLOW_FLAG'], test_x_predictions)
print("Testing Confusion Matrix:\n", cm_test)

# Print precision, recall, accuracy, and F1 score
accuracy = accuracy_score(test_df['LEAK_FLOW_FLAG'], test_x_predictions)
recall = recall_score(test_df['LEAK_FLOW_FLAG'], test_x_predictions, zero_division=0)
precision = precision_score(test_df['LEAK_FLOW_FLAG'], test_x_predictions, zero_division=0)
f1 = f1_score(test_df['LEAK_FLOW_FLAG'], test_x_predictions, zero_division=0)

print(f'Accuracy: {accuracy}')
print(f'Recall: {recall}')
print(f'Precision: {precision}')
print(f'F1 Score: {f1}')


Training Confusion Matrix:
 [[286917   6638]
 [ 25152   1363]]
Testing Confusion Matrix:
 [[48240  1284]
 [ 6892    68]]
Accuracy: 0.8552510445435876
Recall: 0.009770114942528735
Precision: 0.05029585798816568
F1 Score: 0.016361886429258902


XGBoost

In [10]:
import pandas as pd
import numpy as np
from xgboost import XGBClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import GridSearchCV

# Feature selection for XGBoost
drop_columns = ['UTC_TIME', 'FLIGHT_ID', 'MSN']
selected_features = [
    'VALUE_FOB', 'EXPECTED_FOB', 'VALUE_FUEL_QTY_RXT', 'TOTAL_FUEL_LW',
    'VALUE_FUEL_QTY_LXT', 'TOTAL_FUEL_RW', 'FUEL_IN_TANKS', 'LEAK_FLOW_FLAG','FUEL_USED_4','TOTAL_FUEL_USED','FUEL_USED_3']

          
        



# Ensure rolling features exist before selecting features
train_df['VALUE_FOB_mean'] = train_df['VALUE_FOB'].rolling(window=10).mean()
train_df['VALUE_FOB_mean'] = train_df['VALUE_FOB_mean'].fillna(train_df['VALUE_FOB_mean'].mean())
train_df['lagged'] = train_df['VALUE_FOB'].shift(1).fillna(train_df['VALUE_FOB'].mean())
test_df['VALUE_FOB_mean'] = test_df['VALUE_FOB'].rolling(window=10).mean()
test_df['VALUE_FOB_mean'] = test_df['VALUE_FOB_mean'].fillna(test_df['VALUE_FOB_mean'].mean())
test_df['lagged'] = test_df['VALUE_FOB'].shift(1).fillna(test_df['VALUE_FOB'].mean())

# Add rolling features to selected features
selected_features.extend(['VALUE_FOB_mean', 'lagged'])

xgboostdata = train_df[selected_features]

# Ensure test set contains all necessary features
X_train = xgboostdata.drop(columns=['LEAK_FLOW_FLAG'])
y_train = xgboostdata['LEAK_FLOW_FLAG']
X_test = test_df[selected_features].drop(columns=['LEAK_FLOW_FLAG'], errors='ignore')
y_test = test_df['LEAK_FLOW_FLAG']

# Normalize the data
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train XGBoost classifier
xgb = XGBClassifier()
xgb.fit(X_train_scaled, y_train)

# Predictions
train_x_predictions = xgb.predict(X_train_scaled)
test_x_predictions = xgb.predict(X_test_scaled)

# Evaluate performance
cm_train = confusion_matrix(y_train, train_x_predictions)
cm_test = confusion_matrix(y_test, test_x_predictions)

accuracy = accuracy_score(y_test, test_x_predictions)
recall = recall_score(y_test, test_x_predictions, zero_division=0)
precision = precision_score(y_test, test_x_predictions, zero_division=0)
f1 = f1_score(y_test, test_x_predictions, zero_division=0)

print("Training Confusion Matrix:\n", cm_train)
print("Testing Confusion Matrix:\n", cm_test)
print(f'Accuracy: {accuracy}')
print(f'Recall: {recall}')
print(f'Precision: {precision}')
print(f'F1 Score: {f1}')

# Feature importance
feature_importances = xgb.feature_importances_
features = X_train.columns
feature_importances_df = pd.DataFrame({'Feature': features, 'Importance': feature_importances})
feature_importances_df = feature_importances_df.sort_values(by='Importance', ascending=False)
print(feature_importances_df)



c:\Users\gabri\anaconda3\Lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[23:35:10] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Training Confusion Matrix:
 [[287860   5695]
 [ 16250  10265]]
Testing Confusion Matrix:
 [[49232   292]
 [ 6635   325]]
Accuracy: 0.8773635011684725
Recall: 0.04669540229885057
Precision: 0.526742301458671
F1 Score: 0.0857859311072984
               Feature  Importance
5        TOTAL_FUEL_RW    0.146212
4   VALUE_FUEL_QTY_LXT    0.127165
2   VALUE_FUEL_QTY_RXT    0.124556
3        TOTAL_FUEL_LW    0.119816
7          FUEL_USED_4    0.099216
6        FUEL_IN_TANKS    0.079493
1         EXPECTED_FOB    0.073321
9          FUEL_USED_3    0.066042
8      TOTAL_FUEL_USED    0.061626
11              lagged    0.041035
0            VALUE_FOB    0.035894
10      VALUE_FOB_mean    0.025626

In [11]:

# Hyperparameter tuning
tuning_params = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [2, 4, 6, 8],
    'learning_rate': [0.01, 0.1, 0.2, 0.3],
    'subsample': [0.5, 0.7, 0.9],
    'colsample_bytree': [0.5, 0.7, 0.9],
}

grid_search = GridSearchCV(estimator=XGBClassifier(n_estimator=100), param_grid=tuning_params, cv=3, scoring='accuracy', verbose=2, n_jobs=-1)
grid_search.fit(X_train_scaled, y_train)

print("Best Parameters:", grid_search.best_params_)
print("Best Score:", grid_search.best_score_)

# Predict with the best model
train_x_predictions = grid_search.best_estimator_.predict(X_train_scaled)
test_x_predictions = grid_search.best_estimator_.predict(X_test_scaled)

# Final evaluation
cm_train = confusion_matrix(y_train, train_x_predictions)
cm_test = confusion_matrix(y_test, test_x_predictions)
accuracy = accuracy_score(y_test, test_x_predictions)
recall = recall_score(y_test, test_x_predictions, zero_division=0)
precision = precision_score(y_test, test_x_predictions, zero_division=0)
f1 = f1_score(y_test, test_x_predictions, zero_division=0)

print("Final Training Confusion Matrix:\n", cm_train)
print("Final Testing Confusion Matrix:\n", cm_test)
print(f'Final Accuracy: {accuracy}')
print(f'Final Recall: {recall}')
print(f'Final Precision: {precision}')
print(f'Final F1 Score: {f1}')

# Print final feature importance
feature_importances = grid_search.best_estimator_.feature_importances_
feature_importances_df = pd.DataFrame({'Feature': features, 'Importance': feature_importances})
feature_importances_df = feature_importances_df.sort_values(by='Importance', ascending=False)
print(feature_importances_df)


Fitting 3 folds for each of 576 candidates, totalling 1728 fits


c:\Users\gabri\anaconda3\Lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[02:57:16] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:573: 
Parameters: { "n_estimator" } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[02:57:16] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Best Parameters: {'colsample_bytree': 0.9, 'learning_rate': 0.01, 'max_depth': 4, 'n_estimators': 150, 'subsample': 0.7}
Best Score: 0.9171993626394226
Final Training Confusion Matrix:
 [[293509     46]
 [ 26438     77]]
Final Testing Confusion Matrix:
 [[49447    77]
 [ 6872    88]]
Final Accuracy

``` python
# Hyperparameter tuning
tuning_params = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [2, 4, 6, 8],
    'learning_rate': [0.01, 0.1, 0.2, 0.3],
    'subsample': [0.5, 0.7, 0.9],
    'colsample_bytree': [0.5, 0.7, 0.9],
}

grid_search = GridSearchCV(estimator=XGBClassifier(), param_grid=tuning_params, cv=3, scoring='accuracy', verbose=2, n_jobs=-1)
grid_search.fit(X_train_scaled, y_train)

print("Best Parameters:", grid_search.best_params_)
print("Best Score:", grid_search.best_score_)

# Predict with the best model
train_x_predictions = grid_search.best_estimator_.predict(X_train_scaled)
test_x_predictions = grid_search.best_estimator_.predict(X_test_scaled)

# Final evaluation
cm_train = confusion_matrix(y_train, train_x_predictions)
cm_test = confusion_matrix(y_test, test_x_predictions)
accuracy = accuracy_score(y_test, test_x_predictions)
recall = recall_score(y_test, test_x_predictions, zero_division=0)
precision = precision_score(y_test, test_x_predictions, zero_division=0)
f1 = f1_score(y_test, test_x_predictions, zero_division=0)

print("Final Training Confusion Matrix:\n", cm_train)
print("Final Testing Confusion Matrix:\n", cm_test)
print(f'Final Accuracy: {accuracy}')
print(f'Final Recall: {recall}')
print(f'Final Precision: {precision}')
print(f'Final F1 Score: {f1}')

# Print final feature importance
feature_importances = grid_search.best_estimator_.feature_importances_
feature_importances_df = pd.DataFrame({'Feature': features, 'Importance': feature_importances})
feature_importances_df = feature_importances_df.sort_values(by='Importance', ascending=False)
print(feature_importances_df)


In [12]:
train_df.columns

Index(['UTC_TIME', 'FUEL_USED_2', 'FUEL_USED_3', 'FUEL_USED_4',
       'FW_GEO_ALTITUDE', 'VALUE_FOB', 'VALUE_FUEL_QTY_CT',
       'VALUE_FUEL_QTY_FT1', 'VALUE_FUEL_QTY_FT2', 'VALUE_FUEL_QTY_FT3',
       'VALUE_FUEL_QTY_FT4', 'VALUE_FUEL_QTY_LXT', 'VALUE_FUEL_QTY_RXT',
       'FUEL_USED_1', 'MSN', 'NEW_FLIGHT', 'FLIGHT_ID', 'START_FOB',
       'TOTAL_FUEL_USED', 'EXPECTED_FOB', 'FOB_DIFFERENCE', 'FOB_CHANGE',
       'EXPECTED_FOB_CHANGE', 'FUEL_LEAK_RATE', 'TOTAL_FUEL_LW',
       'TOTAL_FUEL_RW', 'LW_RW_DIFF', 'FUEL_IN_TANKS', 'CALC_VALUE_FOB_DIFF',
       'START_FOB_VS_FOB_FUELUSED', 'ALTITUDE_DIFF', 'LEAK_FLOW_FLAG',
       'VALUE_FOB_mean', 'lagged'],
      dtype='object')

LSTM

In [13]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from keras.models import Sequential
from keras.layers import LSTM, Dense, Dropout, RepeatVector, TimeDistributed

# Identify numerical columns and scale only those
numerical_cols = train_df.select_dtypes(include=[np.number]).columns
scaler = MinMaxScaler()
train_data_scaled = scaler.fit_transform(train_df[numerical_cols])
test_data_scaled = scaler.transform(test_df[numerical_cols])

# Reshape data for LSTM (samples, timesteps, features)
time_steps = 10  # Number of time steps for LSTM input
train_data_reshaped = train_data_scaled.reshape((train_data_scaled.shape[0], 1, train_data_scaled.shape[1]))
test_data_reshaped = test_data_scaled.reshape((test_data_scaled.shape[0], 1, test_data_scaled.shape[1]))

# Define LSTM Autoencoder model
model = Sequential([
    LSTM(128, activation='relu', input_shape=(1, train_data_scaled.shape[1]), return_sequences=True),
    Dropout(0.2),
    LSTM(64, activation='relu', return_sequences=False),
    RepeatVector(1),
    LSTM(64, activation='relu', return_sequences=True),
    Dropout(0.2),
    LSTM(128, activation='relu', return_sequences=True),
    TimeDistributed(Dense(train_data_scaled.shape[1]))
])

model.compile(optimizer='adam', loss='mse')

# Train the LSTM Autoencoder
model.fit(train_data_reshaped, train_data_reshaped,
          epochs=50,
          batch_size=64,
          validation_split=0.2,
          shuffle=True,
          verbose=1)

# Get reconstruction loss (MSE) on the test data
reconstructions = model.predict(test_data_reshaped)
mse = np.mean(np.power(test_data_reshaped - reconstructions, 2), axis=(1, 2))

# Determine anomaly threshold based on 95th percentile
threshold = np.percentile(mse, 95)

# Detect anomalies based on the threshold
test_df = test_df.copy()
test_df['reconstruction_error'] = mse
test_df['anomaly'] = test_df['reconstruction_error'] > threshold

# Evaluation metrics
y_true = test_df['LEAK_FLOW_FLAG']
y_pred = test_df['anomaly'].astype(int)

conf_matrix = confusion_matrix(y_true, y_pred)
accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, zero_division=0)
recall = recall_score(y_true, y_pred, zero_division=0)
f1 = f1_score(y_true, y_pred, zero_division=0)

# Print evaluation results
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")


c:\Users\gabri\anaconda3\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/50
4001/4001 ━━━━━━━━━━━━━━━━━━━━ 43s 9ms/step - loss: 0.0229 - val_loss: 0.0011
Epoch 2/50
4001/4001 ━━━━━━━━━━━━━━━━━━━━ 33s 8ms/step - loss: 0.0011 - val_loss: 0.0012
Epoch 3/50
4001/4001 ━━━━━━━━━━━━━━━━━━━━ 29s 7ms/step - loss: 6.2579e-04 - val_loss: 0.0020
Epoch 4/50
4001/4001 ━━━━━━━━━━━━━━━━━━━━ 31s 8ms/step - loss: 5.2720e-04 - val_loss: 0.0023
Epoch 5/50
4001/4001 ━━━━━━━━━━━━━━━━━━━━ 32s 8ms/step - loss: 4.7345e-04 - val_loss: 0.0023
Epoch 6/50
4001/4001 ━━━━━━━━━━━━━━━━━━━━ 33s 8ms/step - loss: 4.3821e-04 - val_loss: 0.0024
Epoch 7/50
4001/4001 ━━━━━━━━━━━━━━━━━━━━ 32s 8ms/step - loss: 4.1150e-04 - val_loss: 0.0024
Epoch 8/50
4001/4001 ━━━━━━━━━━━━━━━━━━━━ 31s 8ms/step - loss: 3.8938e-04 - val_loss: 0.0024
Epoch 9/50
4001/4001 ━━━━━━━━━━━━━━━━━━━━ 31s 8ms/step - loss: 3.6577e-04 - val_loss: 0.0029
Epoch 10/50
4001/4001 ━━━━━━━━━━━━━━━━━━━━ 25s 6ms/step - loss: 3.5345e-04 - val_loss: 0.0028
Epoch 11/50
4001/4001 ━━━━━━━━━━━━━━━━━━━━ 26s 6ms/step - loss: 3.3416e-04 - 